# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "The CLI for Humanitec, humctl."
  homepage "https://developer.humanitec.com/platform-orchestrator/cli/"
  version "0.39.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humanitec/cli/releases/download/v0.39.5/cli_0.39.5_darwin_amd64.tar.gz"
      sha256 "1f2078b0061466cf9922ac43cb149130004e30868a534969aaa6154b8412c2f7"

      def install
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humanitec/cli/releases/download/v0.39.5/cli_0.39.5_darwin_arm64.tar.gz"
      sha256 "1bec2ad3d1dc96084e63c7945b10bc87d5e5a025ade47a45550d2f17ab3e0a60"

      def install
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/humanitec/cli/releases/download/v0.39.5/cli_0.39.5_linux_amd64.tar.gz"
      sha256 "67234fff978ead34c30345b2a6a3032cff5d7665ef1d5fc20f6050d51b92bacb"
      def install
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/humanitec/cli/releases/download/v0.39.5/cli_0.39.5_linux_arm64.tar.gz"
      sha256 "923b04159610be64aa865168e1167bccd375d39895766677d6945904e794b838"
      def install
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
  end
end
