# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "The CLI for Humanitec, humctl."
  homepage "https://developer.humanitec.com/platform-orchestrator/cli/"
  version "0.20.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humanitec/cli/releases/download/v0.20.0/cli_0.20.0_darwin_amd64.tar.gz"
      sha256 "644d13d8ba788e5067356886e0bc18b04bac28557742b56dca3682d62ba43966"

      def install
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humanitec/cli/releases/download/v0.20.0/cli_0.20.0_darwin_arm64.tar.gz"
      sha256 "ff5a8fe908a255c06b71e3ce5be9b0d98275d146f917448b0b19f0f9e2279824"

      def install
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/humanitec/cli/releases/download/v0.20.0/cli_0.20.0_linux_amd64.tar.gz"
      sha256 "29b034e7c40271c4782b591cc01e3c7ff2b0b18406220580d075c140a2c5ec93"

      def install
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanitec/cli/releases/download/v0.20.0/cli_0.20.0_linux_arm64.tar.gz"
      sha256 "02e267300307150b7f529b431884ccdfd523c785071e866c3a6f483ffacb2833"

      def install
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
  end
end
