# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "The CLI for Humanitec, humctl."
  homepage "https://developer.humanitec.com/platform-orchestrator/cli/"
  version "0.39.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humanitec/cli/releases/download/v0.39.14/cli_0.39.14_darwin_amd64.tar.gz"
      sha256 "4e0dc203151ce95b9d016a01e8b06cf4527d4c5cbb330b0ca3cda9ed5352cd57"

      define_method(:install) do
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humanitec/cli/releases/download/v0.39.14/cli_0.39.14_darwin_arm64.tar.gz"
      sha256 "03f32ddaecf4edf2b708a9bf04b3a77bbeb1af2c834da8617acc80a0f9c7474d"

      define_method(:install) do
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanitec/cli/releases/download/v0.39.14/cli_0.39.14_linux_amd64.tar.gz"
      sha256 "818e5e73e612a7b019982ec413968369b7176a3344bb83cd4fbdb885b6be1e32"
      define_method(:install) do
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/humanitec/cli/releases/download/v0.39.14/cli_0.39.14_linux_arm64.tar.gz"
      sha256 "64e64c7d2f6fe8cf97439868a795f4721e50471d2ca2cd0bb90be7022fcbcf33"
      define_method(:install) do
        bin.install "humctl"
        generate_completions_from_executable(bin/"humctl", "completion")
      end
    end
  end
end
