# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hctl < Formula
  desc "The CLI for Humanitec Platform Orchestrator, hctl."
  homepage "https://developer.humanitec.com/platform-orchestrator/docs/integrations/cli"
  version "1.34.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humanitec/hctl/releases/download/v1.34.2/hctl_1.34.2_darwin_amd64.tar.gz"
      sha256 "f129b3556eb22efdaa9676636ef3f6e9ff83e61eacc633847f3cb7362be2d0d8"

      def install
        bin.install "hctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humanitec/hctl/releases/download/v1.34.2/hctl_1.34.2_darwin_arm64.tar.gz"
      sha256 "8382cf85b14cc1fc349d8d25bd8ca17e9aba0815f2407772854ef4851b116730"

      def install
        bin.install "hctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/humanitec/hctl/releases/download/v1.34.2/hctl_1.34.2_linux_amd64.tar.gz"
      sha256 "028c257197d3dedff3ab043a75612bafc24a3d9bba35f829073549dbb7d1c61b"
      def install
        bin.install "hctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/humanitec/hctl/releases/download/v1.34.2/hctl_1.34.2_linux_arm64.tar.gz"
      sha256 "0a54090159f2a732ff2a782f803a64c553610f7c02be69d2858de63facd77dfa"
      def install
        bin.install "hctl"
      end
    end
  end
end
